### ISSUE TITLE
I think your nvdaController dlls always claim to be running

### ISSUE THREAD

**Issue by fiendish** [nstockton/mushclient-mume#1]
Hi there. A friend pointed me at your MUSHclient screen reader plugin, but the screen_reader_speak plugin always thinks NVDA is running even though it's not installed. Do you know if this is an issue with the DLL?

**Comment by nstockton** [comment]
Hello Fiendish,
I am unable to reproduce this issue on my machine (Windows 7 Ultimate 32-bit). Would you be able to give me the steps you use to reproduce this issue on your system, as well as which version of windows 32-64-bit you are running?
Note that the DLL files under the "screen_reader_dlls" directory of this repo are taken from the manufacturer of each screen reader.

**Comment by fiendish** [comment]
I'm actually not using Windows. I am using Wine to run MUSHclient on Linux. The Microsoft SAPI text to speech engine can be installed in Wine with the Microsoft Speech SDK installer, but to my knowledge none of the major Windows screen readers can be installed with Wine. When I tested in Windows it does work correctly, so I think there may be a bug in Wine that returns the wrong result when testing for a DLL function. Some other systems that use intermediary DLLs (Davey Kager's Tolk library, QuentinC's UniversalSpeech, and Tyler Spivey's MushReader plugin) seem to work. My guess is that doing the check inside C code bypasses this Wine bug. Anyway if that is the case, then this becomes someone else's bug so I'll close this for now.
