### ISSUE TITLE
Missing files or missing instructions?

### ISSUE THREAD

**Issue by ParadoxiKat** [nstockton/mushclient-mume#2]
Cloning this repo does not result in a complete working copy. lua and Mushclient executables, the mapper proxy, the NVDA addon which are all mentioned in the README are not present.
No instructions are provided in the README, which is otherwise thorough, on how to properly obtain all these components to build a working copy.
Mention is made in the README to "if running from source". This implies a package is available which one assumes would contain all necessary files. However no packages or releases appear to be published, nor does the README make mention of any 3rd party download link for a complete build.

Please update the repo to include all files, or update the README with instructions on how one obtains all working files or a prebuilt package.

**Comment by nstockton** [comment]
Old information has been removed from the ReadMe, and a new release, containing a complete package can now be found in the releases section.
